# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47593174c073d5147e469f649d007e242a907243202f7684ca8bd834cbca5851159bdabcc78827474f8628a31ea15345efb7b297e68c08b2f319c8852c6598ed

test:
  secret_key_base: 7c5329d75c8de71926f6cc62da58c0041f920f16df456673ba45251658c4279c0bdae1ae8e39ec205942829e8beecdc3543d7c5bdc215ab74f028d60ffbb9b85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
